insert into node (label, parent_id, id) values ('root', null, 1)
insert into node (label, parent_id, id) values ('ant', 1, 2)
insert into node (label, parent_id, id) values ('bear', 1, 3)
insert into node (label, parent_id, id) values ('cat', 3, 4)
insert into node (label, parent_id, id) values ('dog', 3, 5)
insert into node (label, parent_id, id) values ('elephant', 5, 6)
insert into node (label, parent_id, id) values ('frog', 1, 7)